//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.Ux.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nat.Ux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificacion incorrecta.
        /// </summary>
        internal static string lioE_CaptchaNo {
            get {
                return ResourceManager.GetString("lioE_CaptchaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Carga de Documentos.
        /// </summary>
        internal static string lioE_DocsLoad {
            get {
                return ResourceManager.GetString("lioE_DocsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Invalido.
        /// </summary>
        internal static string lioE_DocUserNo {
            get {
                return ResourceManager.GetString("lioE_DocUserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud de Archivo no soportada.
        /// </summary>
        internal static string lioE_Large {
            get {
                return ResourceManager.GetString("lioE_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en comunicacion con la capa de servicios..
        /// </summary>
        internal static string lioE_NoApi {
            get {
                return ResourceManager.GetString("lioE_NoApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento No Encontrado.
        /// </summary>
        internal static string lioE_NoPdf {
            get {
                return ResourceManager.GetString("lioE_NoPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento No Distribuido.
        /// </summary>
        internal static string lioE_NoShare {
            get {
                return ResourceManager.GetString("lioE_NoShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Registros de Estados.
        /// </summary>
        internal static string lioE_NoTracking {
            get {
                return ResourceManager.GetString("lioE_NoTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseñas deben Coincidir.
        /// </summary>
        internal static string lioE_PassDif {
            get {
                return ResourceManager.GetString("lioE_PassDif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta no Encotrada.
        /// </summary>
        internal static string lioE_RouteNo {
            get {
                return ResourceManager.GetString("lioE_RouteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesion Expirada, vuelva a autentificarse.
        /// </summary>
        internal static string lioE_TokenExp {
            get {
                return ResourceManager.GetString("lioE_TokenExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Documento.
        /// </summary>
        internal static string lioL_Add {
            get {
                return ResourceManager.GetString("lioL_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Administrador?.
        /// </summary>
        internal static string lioL_Adm {
            get {
                return ResourceManager.GetString("lioL_Adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string lioL_Adv {
            get {
                return ResourceManager.GetString("lioL_Adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuits.
        /// </summary>
        internal static string lioL_Bo {
            get {
                return ResourceManager.GetString("lioL_Bo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string lioL_Cancel {
            get {
                return ResourceManager.GetString("lioL_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el valor en numeros.
        /// </summary>
        internal static string lioL_Captcha {
            get {
                return ResourceManager.GetString("lioL_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar Filtros.
        /// </summary>
        internal static string lioL_Clr {
            get {
                return ResourceManager.GetString("lioL_Clr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string lioL_Cnfg {
            get {
                return ResourceManager.GetString("lioL_Cnfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separados por Coma, [ ] para default.
        /// </summary>
        internal static string lioL_Coma {
            get {
                return ResourceManager.GetString("lioL_Coma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        internal static string lioL_Copy {
            get {
                return ResourceManager.GetString("lioL_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotización U$S: .
        /// </summary>
        internal static string lioL_Ctz {
            get {
                return ResourceManager.GetString("lioL_Ctz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptor.
        /// </summary>
        internal static string lioL_Cuit {
            get {
                return ResourceManager.GetString("lioL_Cuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.U.I.T..
        /// </summary>
        internal static string lioL_Cuit1 {
            get {
                return ResourceManager.GetString("lioL_Cuit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operando con CUIT.
        /// </summary>
        internal static string lioL_CurrentCuit {
            get {
                return ResourceManager.GetString("lioL_CurrentCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Emisión.
        /// </summary>
        internal static string lioL_Date {
            get {
                return ResourceManager.GetString("lioL_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde.
        /// </summary>
        internal static string lioL_DateD {
            get {
                return ResourceManager.GetString("lioL_DateD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta.
        /// </summary>
        internal static string lioL_DateH {
            get {
                return ResourceManager.GetString("lioL_DateH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string lioL_DateLog {
            get {
                return ResourceManager.GetString("lioL_DateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y Hora.
        /// </summary>
        internal static string lioL_DateTime {
            get {
                return ResourceManager.GetString("lioL_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIT predeterminado.
        /// </summary>
        internal static string lioL_DefaultCuit {
            get {
                return ResourceManager.GetString("lioL_DefaultCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Documento.
        /// </summary>
        internal static string lioL_Delete {
            get {
                return ResourceManager.GetString("lioL_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea Eliminar el Documento?.
        /// </summary>
        internal static string lioL_DeleteBody {
            get {
                return ResourceManager.GetString("lioL_DeleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string lioL_Desc {
            get {
                return ResourceManager.GetString("lioL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string lioL_Detail {
            get {
                return ResourceManager.GetString("lioL_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Emitidos.
        /// </summary>
        internal static string lioL_Docs {
            get {
                return ResourceManager.GetString("lioL_Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        internal static string lioL_Documents {
            get {
                return ResourceManager.GetString("lioL_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrastre o Click para buscar.
        /// </summary>
        internal static string lioL_Drag {
            get {
                return ResourceManager.GetString("lioL_Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string lioL_Edit {
            get {
                return ResourceManager.GetString("lioL_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        internal static string lioL_Email {
            get {
                return ResourceManager.GetString("lioL_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisor.
        /// </summary>
        internal static string lioL_Emisor {
            get {
                return ResourceManager.GetString("lioL_Emisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitado.
        /// </summary>
        internal static string lioL_Enable {
            get {
                return ResourceManager.GetString("lioL_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string lioL_Encoding {
            get {
                return ResourceManager.GetString("lioL_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string lioL_Error {
            get {
                return ResourceManager.GetString("lioL_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado ET.
        /// </summary>
        internal static string lioL_ETsts {
            get {
                return ResourceManager.GetString("lioL_ETsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Evento.
        /// </summary>
        internal static string lioL_Event {
            get {
                return ResourceManager.GetString("lioL_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string lioL_Exit {
            get {
                return ResourceManager.GetString("lioL_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Filas.
        /// </summary>
        internal static string lioL_Export {
            get {
                return ResourceManager.GetString("lioL_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Archivo.
        /// </summary>
        internal static string lioL_FileDownload {
            get {
                return ResourceManager.GetString("lioL_FileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar Archivo.
        /// </summary>
        internal static string lioL_FileUpload {
            get {
                return ResourceManager.GetString("lioL_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string lioL_Find {
            get {
                return ResourceManager.GetString("lioL_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa FTP?.
        /// </summary>
        internal static string lioL_Ftp {
            get {
                return ResourceManager.GetString("lioL_Ftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorio de Ingreso de Archivos.
        /// </summary>
        internal static string lioL_FtpIn {
            get {
                return ResourceManager.GetString("lioL_FtpIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorio de Egreso de Archivos.
        /// </summary>
        internal static string lioL_FtpOut {
            get {
                return ResourceManager.GetString("lioL_FtpOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homologación.
        /// </summary>
        internal static string lioL_Homo {
            get {
                return ResourceManager.GetString("lioL_Homo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id..
        /// </summary>
        internal static string lioL_Id {
            get {
                return ResourceManager.GetString("lioL_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lioL_IdCliente {
            get {
                return ResourceManager.GetString("lioL_IdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        internal static string lioL_Importe {
            get {
                return ResourceManager.GetString("lioL_Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        internal static string lioL_In {
            get {
                return ResourceManager.GetString("lioL_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letra.
        /// </summary>
        internal static string lioL_Letra {
            get {
                return ResourceManager.GetString("lioL_Letra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string lioL_Log {
            get {
                return ResourceManager.GetString("lioL_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string lioL_login {
            get {
                return ResourceManager.GetString("lioL_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeador.
        /// </summary>
        internal static string lioL_Mapper {
            get {
                return ResourceManager.GetString("lioL_Mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Perfil.
        /// </summary>
        internal static string lioL_MisDatos {
            get {
                return ResourceManager.GetString("lioL_MisDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        internal static string lioL_Moneda {
            get {
                return ResourceManager.GetString("lioL_Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string lioL_Nbr {
            get {
                return ResourceManager.GetString("lioL_Nbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro. Desde.
        /// </summary>
        internal static string lioL_NbrD {
            get {
                return ResourceManager.GetString("lioL_NbrD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro. Hasta.
        /// </summary>
        internal static string lioL_NbrH {
            get {
                return ResourceManager.GetString("lioL_NbrH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Documento.
        /// </summary>
        internal static string lioL_NewDoc {
            get {
                return ResourceManager.GetString("lioL_NewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lioL_No {
            get {
                return ResourceManager.GetString("lioL_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins Fallidos.
        /// </summary>
        internal static string lioL_NroFails {
            get {
                return ResourceManager.GetString("lioL_NroFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string lioL_Ok {
            get {
                return ResourceManager.GetString("lioL_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación Exitosa.
        /// </summary>
        internal static string lioL_OperOK {
            get {
                return ResourceManager.GetString("lioL_OperOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Recibido.
        /// </summary>
        internal static string lioL_Original {
            get {
                return ResourceManager.GetString("lioL_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string lioL_Pass {
            get {
                return ResourceManager.GetString("lioL_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Contraseña.
        /// </summary>
        internal static string lioL_Pass1 {
            get {
                return ResourceManager.GetString("lioL_Pass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repita Nueva Contraseña.
        /// </summary>
        internal static string lioL_Pass2 {
            get {
                return ResourceManager.GetString("lioL_Pass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        internal static string lioL_PassChg {
            get {
                return ResourceManager.GetString("lioL_PassChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string lioL_Pdf {
            get {
                return ResourceManager.GetString("lioL_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar PDF.
        /// </summary>
        internal static string lioL_PdfGen {
            get {
                return ResourceManager.GetString("lioL_PdfGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar PDF.
        /// </summary>
        internal static string lioL_Print {
            get {
                return ResourceManager.GetString("lioL_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción.
        /// </summary>
        internal static string lioL_Prod {
            get {
                return ResourceManager.GetString("lioL_Prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pto Venta.
        /// </summary>
        internal static string lioL_PV {
            get {
                return ResourceManager.GetString("lioL_PV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        internal static string lioL_Result {
            get {
                return ResourceManager.GetString("lioL_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        internal static string lioL_Rs {
            get {
                return ResourceManager.GetString("lioL_Rs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta Enviada en Archivo .
        /// </summary>
        internal static string lioL_Rta {
            get {
                return ResourceManager.GetString("lioL_Rta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerar Respuesta ARCA.
        /// </summary>
        internal static string lioL_SendResponse {
            get {
                return ResourceManager.GetString("lioL_SendResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribuir.
        /// </summary>
        internal static string lioL_Share {
            get {
                return ResourceManager.GetString("lioL_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Estaticos.
        /// </summary>
        internal static string lioL_Statics {
            get {
                return ResourceManager.GetString("lioL_Statics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string lioL_Status {
            get {
                return ResourceManager.GetString("lioL_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string lioL_Sts {
            get {
                return ResourceManager.GetString("lioL_Sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versiones de Plantillas.
        /// </summary>
        internal static string lioL_Templates {
            get {
                return ResourceManager.GetString("lioL_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trazabilidad Documento.
        /// </summary>
        internal static string lioL_Tracking {
            get {
                return ResourceManager.GetString("lioL_Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Comprobante.
        /// </summary>
        internal static string lioL_Type {
            get {
                return ResourceManager.GetString("lioL_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string lioL_Type1 {
            get {
                return ResourceManager.GetString("lioL_Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el archivo a procesar.
        /// </summary>
        internal static string lioL_Upload {
            get {
                return ResourceManager.GetString("lioL_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecccione los archivos a procesar.
        /// </summary>
        internal static string lioL_Uploads {
            get {
                return ResourceManager.GetString("lioL_Uploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o Correo Electronico.
        /// </summary>
        internal static string lioL_User {
            get {
                return ResourceManager.GetString("lioL_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación de Usuario.
        /// </summary>
        internal static string lioL_UserId {
            get {
                return ResourceManager.GetString("lioL_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre y Apellido del Usuario.
        /// </summary>
        internal static string lioL_UserName {
            get {
                return ResourceManager.GetString("lioL_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string lioL_Users {
            get {
                return ResourceManager.GetString("lioL_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUITs Asociados.
        /// </summary>
        internal static string lioL_UsrCuit {
            get {
                return ResourceManager.GetString("lioL_UsrCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar.
        /// </summary>
        internal static string lioL_Verif {
            get {
                return ResourceManager.GetString("lioL_Verif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperando Documentos....
        /// </summary>
        internal static string lioL_Wait {
            get {
                return ResourceManager.GetString("lioL_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string lioL_Yes {
            get {
                return ResourceManager.GetString("lioL_Yes", resourceCulture);
            }
        }
    }
}
